version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.csv

  4wk_onboarding:
    run: r:latest analysis/report.R
    needs: [generate_study_population]
    outputs:
      moderately_sensitive:
       #cohort1: output/plot_postOp_mortality_30day.png
       subtable_table1_ageGroup: output/table1_ageGroup.csv
       subtable_table1_Sex: output/table1_Sex.csv
       subtable_table1_30dayMortality: output/table1_postOp_mortality_30day.csv
       table1_df_4wk: output/table1_4wk_onboarding.csv
       #table1_kable_4wk: output/Table1_4wk_onboarding.png