version: '3.0'

expectations:
  population_size: 1000

actions:

    generate_study_population:
        run: cohortextractor:latest generate_cohort --study-definition study_definition
        outputs:
            highly_sensitive:
                cohort: output/input.csv

    generate_study_population_cohort_check:
        run: cohortextractor:latest generate_cohort --study-definition study_definition_flow_chart
        outputs:
            highly_sensitive:
                cohort: output/input_*.csv
                
    generate_study_population_vacc_check:
        run: cohortextractor:latest generate_cohort --study-definition study_definition_vacc_check
        outputs:
            highly_sensitive:
                cohort: output/input_vacc_check.csv
            
    check_cohort:
        run: r:latest analysis/check_cohort.R
        needs: [generate_study_population_cohort_check]
        outputs:
            moderately_sensitive:
                cohort: output/check_cohort.csv
                
    4wk_onboarding:
        run: r:latest analysis/report.R
        needs: [generate_study_population]
        outputs:
            moderately_sensitive:
                n_patients: output/count_patients.csv
                #cohort1: output/plot_postOp_mortality_30day.png
                subtable_table1_ageGroup: output/table1_ageGroup.csv
                subtable_table1_Sex: output/table1_Sex.csv
                subtable_table1_30dayMortality: output/table1_postOp_mortality_30day.csv
                table1_df_4wk: output/table1_4wk_onboarding.csv
                #table1_kable_4wk: output/Table1_4wk_onboarding.png
                subtable_table1_ageGroup_3mths: output/table1_ageGroup_3mths.csv
                subtable_table1_Sex_3mths: output/table1_Sex_3mths.csv
                subtable_table1_30dayMortality_3mths: output/table1_postOp_mortality_30day_3mths.csv
                table1_df_4wk_3mths: output/table1_4wk_onboarding_3mths.csv
                #table1_kable_4wk_3mths: output/Table1_4wk_onboarding_3mths.png
                subtable_table1_ageGroup_6mths: output/table1_ageGroup_6mths.csv
                subtable_table1_Sex_6mths: output/table1_Sex_6mths.csv
                subtable_table1_30dayMortality_6mths: output/table1_postOp_mortality_30day_6mths.csv
                table1_df_4wk_6mths: output/table1_4wk_onboarding_6mths.csv
                #table1_kable_4wk_6mths: output/Table1_4wk_onboarding_6mths.png
                tableVacc_30dayMortality: output/tableVacc_postOp_mortality_30day.csv
                tableVacc_df: output/table_Vaccination_status.csv
                #tableVacc_kable: output/TableVacc.png
                tableVacc_30dayMortality_3mths: output/tableVacc_postOp_mortality_30day_3mths.csv
                tableVacc_df_3mths: output/table_Vaccination_status_3mths.csv
                #tableVacc_kable_3mths: output/TableVacc_3mths.png
                tableVacc_30dayMortality_6mths: output/tableVacc_postOp_mortality_30day_6mths.csv
                tableVacc_df_6mths: output/table_Vaccination_status_6mths.csv
                #tableVacc_kable_6mths: output/TableVacc_6mths.png
    
    vacc_definition_check:
        run: r:latest analysis/vacc_check.R
        needs: [generate_study_population_vacc_check]
        outputs:
            moderately_sensitive:
                tableVacc_30dayMortality_3mths_SNOMED: output/Tables_raw output/SNOMED_tableVacc_postOp_mortality_30day_3mths.csv
                tableVacc_30dayMortality_3mths_TPP: output/Tables_raw output/TPP_tableVacc_postOp_mortality_30day_3mths.csv
                tableVacc_30dayMortality_3mths_AlwynSNOMED: output/Tables_raw output/AlwynSNOMED_tableVacc_postOp_mortality_30day_3mths.csv
                tableVacc_30dayMortality_3mths_AlwynTPP: output/Tables_raw output/AlwynTPP_tableVacc_postOp_mortality_30day_3mths.csv
                tableVacc_df_check_3mths_SNOMED: output/Tables_raw output/SNOMED_table_Vaccination_status_3mths.csv
                tableVacc_df_check_3mths_TPP: output/Tables_raw output/TPP_table_Vaccination_status_3mths.csv
                tableVacc_df_check_3mths_AlwynSNOMED: output/Tables_raw output/AlwynSNOMED_table_Vaccination_status_3mths.csv
                tableVacc_df_check_3mths_AlwynTPP: output/Tables_raw output/AlwynTPP_table_Vaccination_status_3mths.csv
                
                