version: '3.0'

expectations:
  population_size: 1500000

actions:


    tibble_test:
        run: r:latest analysis/tibble_test.R
        outputs:
            moderately_sensitive:
                output: output/myTibble.csv
    # generate_study_population:
        # run: cohortextractor:latest generate_cohort --study-definition study_definition
        # outputs:
            # highly_sensitive:
                # cohort: output/input.csv
                
    generate_study_population_2:
        run: cohortextractor:latest generate_cohort --study-definition study_definition_2
        outputs:
            highly_sensitive:
                cohort: output/input_2.csv

    # generate_study_population_cohort_check:
        # run: cohortextractor:latest generate_cohort --study-definition study_definition_flow_chart
        # outputs:
            # highly_sensitive:
                # cohort: output/input_*.csv
            
    # generate_study_population_codelist_check:
        # run: cohortextractor:latest generate_cohort --study-definition study_definition_codelist_check
        # outputs:
            # highly_sensitive:
                # cohort: output/input_*.csv
                
    # generate_study_population_vacc_check_anyTest:
        # run: cohortextractor:latest generate_cohort --study-definition study_definition_vacc_check_anyTest
        # outputs:
            # highly_sensitive:
                # cohort: output/input_vacc_check.csv
    
    # generate_study_population_vacc_check_posTest:
        # run: cohortextractor:latest generate_cohort --study-definition study_definition_vacc_check_posTest
        # outputs:
            # highly_sensitive:
                # cohort: output/input_vacc_check_posTest.csv
    
    # check_cohort:
        # run: r:latest analysis/check_cohort.R
        # needs: [generate_study_population_cohort_check]
        # outputs:
            # moderately_sensitive:
                # cohort: output/check_cohort.csv
                
    # check_codelist:
        # run: r:latest analysis/check_codelist.R
        # needs: [generate_study_population_codelist_check]
        # outputs:
            # moderately_sensitive:
                # cohort: output/check_codelist.csv
                
    # 4wk_onboarding:
        # run: r:latest analysis/report.R
        # needs: [generate_study_population]
        # outputs:
            # moderately_sensitive:
                # n_patients: output/count_patients.csv
                ##cohort1: output/plot_postOp_mortality_30day.png
                # subtable_table1_ageGroup: output/table1_ageGroup.csv
                # subtable_table1_Sex: output/table1_Sex.csv
                # subtable_table1_30dayMortality: output/table1_postOp_mortality_30day.csv
                # table1_df_4wk: output/table1_4wk_onboarding.csv
                ##table1_kable_4wk: output/Table1_4wk_onboarding.png
                # subtable_table1_ageGroup_3mths: output/table1_ageGroup_3mths.csv
                # subtable_table1_Sex_3mths: output/table1_Sex_3mths.csv
                # subtable_table1_30dayMortality_3mths: output/table1_postOp_mortality_30day_3mths.csv
                # table1_df_4wk_3mths: output/table1_4wk_onboarding_3mths.csv
                ##table1_kable_4wk_3mths: output/Table1_4wk_onboarding_3mths.png
                # subtable_table1_ageGroup_6mths: output/table1_ageGroup_6mths.csv
                # subtable_table1_Sex_6mths: output/table1_Sex_6mths.csv
                # subtable_table1_30dayMortality_6mths: output/table1_postOp_mortality_30day_6mths.csv
                # table1_df_4wk_6mths: output/table1_4wk_onboarding_6mths.csv
                ##table1_kable_4wk_6mths: output/Table1_4wk_onboarding_6mths.png
                # tableVacc_30dayMortality: output/tableVacc_postOp_mortality_30day.csv
                # tableVacc_df: output/table_Vaccination_status.csv
                ##tableVacc_kable: output/TableVacc.png
                # tableVacc_30dayMortality_3mths: output/tableVacc_postOp_mortality_30day_3mths.csv
                # tableVacc_df_3mths: output/table_Vaccination_status_3mths.csv
                ##tableVacc_kable_3mths: output/TableVacc_3mths.png
                # tableVacc_30dayMortality_6mths: output/tableVacc_postOp_mortality_30day_6mths.csv
                # tableVacc_df_6mths: output/table_Vaccination_status_6mths.csv
                ##tableVacc_kable_6mths: output/TableVacc_6mths.png
    
    # vacc_definition_check_anyTest:
        # run: r:latest analysis/vacc_check.R
        # needs: [generate_study_population_vacc_check_anyTest]
        # outputs:
            # moderately_sensitive:
                # tableVacc_30dayMortality_3mths_SNOMED: output/SNOMED_tableVacc_postOp_mortality_30day_3mths.csv
                # tableVacc_30dayMortality_3mths_TPP: output/TPP_tableVacc_postOp_mortality_30day_3mths.csv
                # tableVacc_30dayMortality_3mths_AlwynSNOMED: output/AlwynSNOMED_tableVacc_postOp_mortality_30day_3mths.csv
                # tableVacc_30dayMortality_3mths_AlwynTPP: output/AlwynTPP_tableVacc_postOp_mortality_30day_3mths.csv
                # tableVacc_df_check_3mths_SNOMED: output/SNOMED_table_Vaccination_status_3mths.csv
                # tableVacc_df_check_3mths_TPP: output/TPP_table_Vaccination_status_3mths.csv
                # tableVacc_df_check_3mths_AlwynSNOMED: output/AlwynSNOMED_table_Vaccination_status_3mths.csv
                # tableVacc_df_check_3mths_AlwynTPP: output/AlwynTPP_table_Vaccination_status_3mths.csv
                
    # vacc_definition_check_posTest:
        # run: r:latest analysis/vacc_check.R
        # needs: [generate_study_population_vacc_check_posTest]
        # outputs:
            # moderately_sensitive:
                # tableVacc_30dayMortality_3mths_SNOMED: output/SNOMED_tableVacc_postOp_mortality_30day_3mths.csv
                # tableVacc_30dayMortality_3mths_TPP: output/TPP_tableVacc_postOp_mortality_30day_3mths.csv
                # tableVacc_30dayMortality_3mths_AlwynSNOMED: output/AlwynSNOMED_tableVacc_postOp_mortality_30day_3mths.csv
                # tableVacc_30dayMortality_3mths_AlwynTPP: output/AlwynTPP_tableVacc_postOp_mortality_30day_3mths.csv
                # tableVacc_df_check_3mths_SNOMED: output/SNOMED_table_Vaccination_status_3mths.csv
                # tableVacc_df_check_3mths_TPP: output/TPP_table_Vaccination_status_3mths.csv
                # tableVacc_df_check_3mths_AlwynSNOMED: output/AlwynSNOMED_table_Vaccination_status_3mths.csv
                # tableVacc_df_check_3mths_AlwynTPP: output/AlwynTPP_table_Vaccination_status_3mths.csv
                
    # NO LONGER POSSIBLE BECAUSE NUMBERS ARE TOO SMALL
    # sensitivity_analysis_plots:
        # run: r:latest analysis/Make_table_COVIDSurg_compare.R
        # needs: [generate_study_population_2]
        # outputs:
            # moderately_sensitive:
                # figure_NC_2m: output/noCancer__2monthly_summary_proportion_surgeries_within_7wks_after_pos_test.png
                # figure_NC_1m: output/noCancer__1monthly_summary_proportion_surgeries_within_7wks_after_pos_test.png
                # figure_NC_wk: output/noCancer__weekly_summary_proportion_surgeries_within_7wks_after_pos_test.png
                # figure_C3m_2m: output/cancer_3months__2monthly_summary_proportion_surgeries_within_7wks_after_pos_test.png
                # figure_C3m_1m: output/cancer_3months__1monthly_summary_proportion_surgeries_within_7wks_after_pos_test.png
                # figure_C3m_wk: output/cancer_3months__weekly_summary_proportion_surgeries_within_7wks_after_pos_test.png
                # figure_C6m_2m: output/cancer_6months__2monthly_summary_proportion_surgeries_within_7wks_after_pos_test.png
                # figure_C6m_1m: output/cancer_6months__1monthly_summary_proportion_surgeries_within_7wks_after_pos_test.png
                # figure_C6m_wk: output/cancer_6months__weekly_summary_proportion_surgeries_within_7wks_after_pos_test.png
                # figure_AdmMethod_2m: output/__stratified_2monthly_summary_proportion_surgeries_within_7wks_after_pos_test.png
                # figure_AdmMethod_1m: output/__stratified_1monthly_summary_proportion_surgeries_within_7wks_after_pos_test.png
                # figure_AdmMethod_wk: output/__stratified_weekly_summary_proportion_surgeries_within_7wks_after_pos_test.png
                
    sensitivity_analysis_tables:
        run:    r:latest analysis/Make_all_Table1s.R
        needs: [generate_study_population_2]
        outputs:
            moderately_sensitive:
                table1Demogs_PP_3mths: output/table1Demogs_PP_C_within3m.csv
                table1Outcomes_PP_C_within3m: output/table1Outcomes_PP_C_within3m.csv
                table1Demogs_CSP_C_within3m: output/table1Demogs_CSP_C_within3m.csv
                table1Outcomes_CSP_C_within3m: output/table1Outcomes_CSP_C_within3m.csv
                table1Demogs_PNV_C_within3m: output/table1Demogs_PNV_C_within3m.csv
                table1Outcomes_PNV_C_within3m: output/table1Outcomes_PNV_C_within3m.csv
                table1Demogs_PWV_C_within3m: output/table1Demogs_PWV_C_within3m.csv
                table1Outcomes_PWV_C_within3m: output/table1Outcomes_PWV_C_within3m.csv
                table1Demogs_PP_C_within6m: output/table1Demogs_PP_C_within6m.csv
                table1Outcomes_PP_C_within6m: output/table1Outcomes_PP_C_within6m.csv
                table1Demogs_CSP_C_within6m: output/table1Demogs_CSP_C_within6m.csv
                table1Outcomes_CSP_C_within6m: output/table1Outcomes_CSP_C_within6m.csv
                table1Demogs_PNV_C_within6m: output/table1Demogs_PNV_C_within6m.csv
                table1Outcomes_PNV_C_within6m: output/table1Outcomes_PNV_C_within6m.csv
                table1Demogs_PWV_C_within6m: output/table1Demogs_PWV_C_within6m.csv
                table1Outcomes_PWV_C_within6m: output/table1Outcomes_PWV_C_within6m.csv
                table1Demogs_CSP_7wkThreshold: output/table1Demogs_CSP_all_7wkThreshold.csv
                table1Outcomes_CSP_7wkThreshold: output/table1Outcomes_CSP_all_7wkThreshold.csv
                table1Demogs_PNV_7wkThreshold: output/table1Demogs_PNV_all_7wkThreshold.csv
                table1Outcomes_PNV_7wkThreshold: output/table1Outcomes_PNV_all_7wkThreshold.csv
                table1Demogs_PWV_7wkThreshold: output/table1Demogs_PWV_all_7wkThreshold.csv
                table1Outcomes_PWV_7wkThreshold: output/table1Outcomes_PWV_all_7wkThreshold.csv
                table1Demogs_CSP_C_within3m_7wkThreshold: output/table1Demogs_CSP_C_within3m_7wkThreshold.csv
                table1Outcomes_CSP_C_within3m_7wkThreshold: output/table1Outcomes_CSP_C_within3m_7wkThreshold.csv
                table1Demogs_PNV_C_within3m_7wkThreshold: output/table1Demogs_PNV_C_within3m_7wkThreshold.csv
                table1Outcomes_PNV_C_within3m_7wkThreshold: output/table1Outcomes_PNV_C_within3m_7wkThreshold.csv
                table1Demogs_PWV_C_within3m_7wkThreshold: output/table1Demogs_PWV_C_within3m_7wkThreshold.csv
                table1Outcomes_PWV_C_within3m_7wkThreshold: output/table1Outcomes_PWV_C_within3m_7wkThreshold.csv
                table1Demogs_CSP_C_within6m_7wkThreshold: output/table1Demogs_CSP_C_within6m_7wkThreshold.csv
                table1Outcomes_CSP_C_within6m_7wkThreshold: output/table1Outcomes_CSP_C_within6m_7wkThreshold.csv
                table1Demogs_PNV_C_within6m_7wkThreshold: output/table1Demogs_PNV_C_within6m_7wkThreshold.csv
                table1Outcomes_PNV_C_within6m_7wkThreshold: output/table1Outcomes_PNV_C_within6m_7wkThreshold.csv
                table1Demogs_PWV_C_within6m_7wkThreshold: output/table1Demogs_PWV_C_within6m_7wkThreshold.csv
                table1Outcomes_PWV_C_within6m_7wkThreshold: output/table1Outcomes_PWV_C_within6m_7wkThreshold.csv

    output_for_publication:
            run:    r:latest analysis/outputs_for_1st_publication.R
            needs: [generate_study_population_2]
            outputs:
                moderately_sensitive:
                    table1Demogs_PP_all: output/table1Demogs_PP_all.csv
                    table1Demogs_PNV_all: output/table1Demogs_PNV_all.csv
                    table1Demogs_CSP_all: output/table1Demogs_CSP_all.csv
                    table1Demogs_PWV_all: output/table1Demogs_PWV_all.csv
                    table1Outcomes_PP_all: output/table1Outcomes_PP_all.csv
                    table1Outcomes_PNV_all: output/table1Outcomes_PNV_all.csv
                    table1Outcomes_CSP_all: output/table1Outcomes_CSP_all.csv
                    table1Outcomes_PWV_all: output/table1Outcomes_PWV_all.csv
                    TableEra: output/TableEra.csv
                    table_counts: output/table_Count_of_patients_in_each_cohort_in_each_era_across_all_intervals.csv
                    table_counts_7wkThreshold: output/table_7wkThreshold_Count_of_patients_in_each_cohort_in_each_era_across_all_intervals.csv
                    table_mortality_intervals: output/table_30day_post-op_mortality_in_each_era_across_all_intervals.csv
                    table_mortality_intervals_7wkThreshold: output/table_7wkThreshold_30day_post-op_mortality_in_each_era_across_all_intervals.csv
                    table_mortality_totals: output/table_30day_post-op_mortality_for_each_cohort_in_each_era.csv
                    plotData_C3m: output/plotData_C3m.csv
                    plotData_C6m: output/plotData_C6m.csv
                    plotData_NC: output/plotData_NC.csv
                    plotData_AdmMethod: output/plotData_AdmMethod.csv
                    figure_NC_3m: output/noCancer__6monthly_summary_proportion_surgeries_within_7wks_after_pos_test.jpeg
                    figure_C3m_3m: output/cancer_3months__6monthly_summary_proportion_surgeries_within_7wks_after_pos_test.jpeg
                    figure_C6m_3m: output/cancer_6months__6monthly_summary_proportion_surgeries_within_7wks_after_pos_test.jpeg
                    figure_AdmMethod_3m: output/__stratified_6monthly_summary_proportion_surgeries_within_7wks_after_pos_test.jpeg
                    
    admission_check:
        run: r:latest analysis/admission_check.R
        needs: [generate_study_population_2]
        outputs:
            moderately_sensitive:
                tbl_admission_check: output/tbl_admission_check.csv